### ISSUE TITLE
Markdown not properly rendered

### ISSUE THREAD

**Issue by leohhhn** [gnolang/gno-by-example#169]
## Description

I realized that some markdown is not properly rendered: 

```md
---
title: Sending native coins in Gno
section: Chain
---

By using the Banker module, you are able to send native Gno coins, such as `ugnot` 
from one address to another. Each realm can inject the Banker module into the Gno
runtime and can cast it into a specific type of Banker. Each Banker type has its 
own set of access rights for security reasons. Banker types are the following:

- `BankerTypeReadonly` - read-only access to coin balances,
- `BankerTypeOrigSend` - full access to coins sent with the transaction that 
calls the banker,
- `BankerTypeRealmSend` - full access to coins that the realm itself owns,
including the ones sent with the transaction,
- `BankerTypeRealmIssue` - able to issue new coins.
```

As is currently on 
![Screenshot 2024-05-06 at 14 44 24](https://github.com/gnolang/gno-by-example/assets/33522493/ed4fceaa-cb65-475f-be6b-a6910a6fae60)

While the break lines should not affect the render, like below:
![Screenshot 2024-05-06 at 14 45 05](https://github.com/gnolang/gno-by-example/assets/33522493/8f87094b-dd58-4d34-b210-2c8cb34befad)

**Comment by alexiscolin** [comment]
@leohhhn This happens because you use a list symbol just after another parsed inline-block (the code one). It's a bug due to the markdown parser (markdown-to-jsw) that is known... You can try and you will have the same result here: https://markdown-to-jsx.quantizor.dev/

I'm gonna try to use another parser but meanwhile, if it's urgent, you can easily post the new content by avoiding this "-" symbol. You can use the long dash `—` or a `:` instead.
